name: Licences

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  licences:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: preset-nz/compliance@v0.1.0
        with:
          args: licences check
